# HikariCP configuration properties
# MYSQL
jdbcUrl=jdbc:mysql://172.16.0.12:3306/wilmuppkp?useUnicode=yes&characterEncoding=UTF-8
username=ilmuweb
password=ilmuweb
driverClassName=com.mysql.jdbc.Driver
connectionTimeout=30000
maximumPoolSize=10
dbtype=mysql